name: module_auth
description: A new Flutter package project.
version: 0.0.1
author: KodeSmil authors
homepage: kodesmil.com

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:

  shared_preferences: ^0.5.4+6
  http: ^0.12.0+2
  f_logs: ^1.2.1
  provider: ^3.2.0
  validators: ^2.0.0+1
  dio: 2.1.13
  flutter_dotenv: ^2.1.0

  flutter_mobx: ^0.3.6
  mobx: ^0.4.0+1
  mobx_codegen: ^0.3.13
  json_serializable: ^3.2.3

  lib_di:
    path: ../lib_di
  lib_lego:
    path: ../lib_lego
  lib_locale:
    path: ../lib_locale

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
