container:
  image: cirrusci/flutter:latest

abli_task:
  env:
    PATH: $HOME/.pub-cache/bin:${PATH}
  pub_cache:
    folder: ~/.pub-cache

  matrix:
    - name: Setup
      install_grind_script: pub global activate grinder
      pub_upgrade_script: flutter pub upgrade
      install_script: grind pubget --dir=apps/ably
    - name: Lint
      # lint_script: grind lint
    - name: Test
      # test_script: grind test
    - name: Deploy
      depends_on:
        - Setup
        - Lint
        - Test
      only_if: $BRANCH == "dev"
      osx_instance:
        image: catalina-flutter
      install_grind_script: pub global activate grinder
      pub_upgrade_script: flutter pub upgrade
      firebase_cli_install_script: curl -sL https://firebase.tools | bash
      install_script: grind pubget --dir=apps/ably
      bundle_install_script: grind bundleinstall --dir=apps/ably/ios
      build_script: grind build --env=qa --platform=ios --dir=apps/ably/ios
      deploy_script: grind deploy --env=qa --platform=ios --dir=apps/ably/ios