os: osx
language: objective-c
osx_image: xcode11.3

before_install:
  - bundle config path $HOME/.gem-cache
  - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin/:$HOME/.pub-cache/bin:$PATH
  - git clone https://github.com/flutter/flutter.git $HOME/flutter -b beta  --depth 1
  - openssl aes-256-cbc -K $encrypted_12eaa4ded41a_key -iv $encrypted_12eaa4ded41a_iv -in config.tar.enc -out config.tar -d
  - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
  - tar xvf config.tar

before_script:
  - flutter pub upgrade
  - curl -sL https://firebase.tools | bash

jobs:
  include:
    # - stage: test_lint
      # script: 
        # - cd apps/ably/
        # - flutter lint
        # - flutter test
    - stage: deploy_ios_qa
      if: branch = dev
      script: 
        - cd apps/ably/ios
        - bundle install
        - bundle exec fastlane ios build_qa
        - bundle exec fastlane ios deploy_qa
    - stage: deploy_android_qa
      if: branch = dev
      script:
        - brew cask install android-sdk
        - cd apps/ably/android
        - export ANDROID_HOME=/usr/local/share/android-sdk
        - bundle install
        - bundle exec fastlane android build_qa
        - bundle exec fastlane android deploy_qa
    - stage: deploy_ios_prod
      if: branch = master
      script: 
        - cd apps/ably/ios
        - bundle install
        - bundle exec fastlane ios build_prod
        - bundle exec fastlane ios deploy_prod
    - stage: deploy_android_prod
      if: branch = master
      script:
        - brew cask install android-sdk
        - export ANDROID_HOME=/usr/local/share/android-sdk
        - cd apps/ably/android
        - bundle install
        - bundle exec fastlane android build_prod
        - bundle exec fastlane android deploy_prod

cache:
  directories:
    - "$HOME/.pub-cache"
    - "$HOME/.gem-cache"
    - "$HOME/Library/Caches/CocoaPods"
