name: kodesmil_mobile
description: A flutter boilerplate project created using MobX and Provider.
version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  intl_translation: ^0.17.7
  grinder: ^0.8.3+1