name: boilerplate
description: A flutter boilerplate project created using MobX and Provider.

version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4+6
  http: ^0.12.0+2
  flutter_launcher_icons: ^0.7.4
  f_logs: ^1.2.1
  provider: ^3.2.0
  validators: ^2.0.0+1
  dio: 2.1.13
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  flushbar: ^1.9.1
  fit_kit: ^1.1.0
  firebase_crashlytics: ^0.1.2+4
  charts_flutter: ^0.8.1
  firebase_admob: ^0.9.0+10
  flutter_dotenv: ^2.1.0

  lib_auth:
    path: lib_auth

dependency_overrides:
  source_gen: 0.9.4+6
  analyzer: ^0.39.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.2
  grinder: ^0.8.3+1

  inject_generator:
    git:
      url: https://github.com/AndreySouza1/inject.dart.git
      ref: develop
      path: package/inject_generator

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/icons/
  - .env

  fonts:
  - family: ProductSans
    fonts:
    - asset: assets/fonts/Product-Sans-Regular.ttf
    - asset: assets/fonts/Product-Sans-Italic.ttf
      style: italic
    - asset: assets/fonts/Product-Sans-Bold.ttf
      weight: 700
