name: boilerplate
description: A flutter boilerplate project created using MobX and Provider.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4+6
  http: ^0.12.0+2
  flutter_launcher_icons: ^0.7.4
  f_logs: ^1.2.1
  provider: ^3.2.0
  validators: ^2.0.0+1
  dio: 2.1.13
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  flushbar: ^1.9.1
  fit_kit: ^1.1.0
  firebase_crashlytics: ^0.1.2+4
  charts_flutter: ^0.8.1
  firebase_admob: ^0.9.0+10
  flutter_dotenv: ^2.1.0

  flutter_mobx: ^0.3.6
  mobx: ^0.4.0+1
  mobx_codegen: ^0.3.13
  json_serializable: ^3.2.3

  lib_auth:
    path: lib_auth
  lib_di:
    path: lib_di

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.2
  grinder: ^0.8.3+1

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/icons/
  - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: ProductSans
    fonts:
    - asset: assets/fonts/Product-Sans-Regular.ttf
    - asset: assets/fonts/Product-Sans-Italic.ttf
      style: italic
    - asset: assets/fonts/Product-Sans-Bold.ttf
      weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
