name: feat_auth
description: A new Flutter package project.
version: 0.0.1
author: KodeSmil authors
homepage: kodesmil.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  shared_preferences: ^0.5.4+6
  http: ^0.12.0+2
  f_logs: ^1.2.1
  provider: ^4.0.4
  validators: ^2.0.0+1
  dio: ^3.0.9
  flutter_dotenv: ^2.1.0

  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  json_serializable: ^3.2.3
  flutter_svg: ^0.17.2

  google_sign_in: ^4.1.4
  firebase_auth: ^0.16.1

  lib_shared:
    path: ../../libs/lib_shared
  lib_lego:
    path: ../../libs/lib_lego

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
