name: feat_journal
description: A new Flutter package project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  json_serializable: ^3.2.3
  intl: ^0.16.0
  google_sign_in: ^4.1.4
  provider: ^4.0.4
  smooth_star_rating: ^1.0.4+2
  crossplat_objectid: ^2.1.4
  firebase_auth: ^0.16.1
  grpc: ^2.1.3
  table_calendar: ^2.2.3
  flutter_staggered_grid_view: ^0.3.0
  more: ^2.3.1
  jiffy: ^3.0.1
  scrollable_positioned_list: ^0.1.6
  scroll_to_index: ^1.0.6
  flutter_svg: ^0.17.4
  dots_indicator: ^1.1.0
  flutter_translate: ^1.1.0
  infinite_listview: ^1.0.1+1

  lib_di:
    path: ../../libs/lib_di
  lib_lego:
    path: ../../libs/lib_lego
  lib_services:
    path: ../../libs/lib_services
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
