name: lib_locale
description: A new Flutter package project.
version: 0.0.1
author: KodeSmil authors
homepage: kodesmil.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  intl: ^0.16.0
  intl_translation: ^0.17.7

  flutter_mobx: ^0.3.6
  mobx: ^0.4.0+1
  mobx_codegen: ^0.3.13
  json_serializable: ^3.2.3

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
