name: feat_sensors
description: A new Flutter package project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_sensors: ^0.1.6
  csv: ^4.0.3
  flutter_email_sender: ^2.2.2
  path_provider: ^1.6.0
  archive: ^2.0.11
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  json_serializable: ^3.2.3
  intl: ^0.16.0
  lib_shared:
    path: ../../libs/lib_shared
  lib_lego:
    path: ../../libs/lib_lego
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
