name: legobook
description: A new Flutter project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.1

  lib_lego:
    path: ../../libs/lib_lego

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.otf
        - asset: assets/fonts/Inter/Inter-Italic.otf
          style: italic
