name: feat_feed
description: A new Flutter package project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.1.0
  flutter_markdown: ^0.3.5
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  json_serializable: ^3.2.3
  intl: ^0.16.0
  google_sign_in: ^4.1.4
  provider: ^4.0.4
  smooth_star_rating: ^1.1.1
  crossplat_objectid: ^2.1.4
  firebase_auth: ^0.18.0+1
  grpc: ^2.1.3
  flutter_staggered_grid_view: ^0.3.0

  lib_shared:
    path: ../../libs/lib_shared
  lib_lego:
    path: ../../libs/lib_lego
  lib_services:
    path: ../../libs/lib_services
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
