name: module_sensors
description: A new Flutter package project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter_sensors: ^0.1.5
  flutter_mobx: ^0.3.6
  mobx: ^0.4.0+1
  mobx_codegen: ^0.3.13
  json_serializable: ^3.2.3
  intl: ^0.16.0
  lib_di:
    path: ../lib_di
  lib_lego:
    path: ../lib_lego
  lib_locale:
    path: ../lib_locale
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
