name: feat_health_survey
description: A new Flutter package project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter_mobx: ^0.3.6
  mobx: ^0.4.0+1
  mobx_codegen: ^0.3.13
  json_serializable: ^3.2.3
  intl: ^0.16.0
  google_sign_in: ^4.1.4
  provider: ^4.0.4
  smooth_star_rating: ^1.0.4+2

  feat_auth:
    path: ../feat_auth
  lib_di:
    path: ../../libs/lib_di
  lib_lego:
    path: ../../libs/lib_lego
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
