name: feat_template
description: A new Flutter package project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  json_serializable: ^3.2.3
  intl: ^0.16.0
  google_sign_in: ^4.1.4
  provider: ^4.0.4

  feat_auth:
    path: ../feat_auth
  lib_di:
    path: ../../libs/lib_di
  lib_lego:
    path: ../../libs/lib_lego
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
