name: lib_auth
description: A new Flutter package project.
version: 0.0.1
author:
homepage: kodesmil.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  shared_preferences: ^0.5.4+6
  http: ^0.12.0+2
  f_logs: ^1.2.1
  flutter_mobx: ^0.3.6
  mobx: ^0.4.0+1
  mobx_codegen: ^0.3.13
  provider: ^3.2.0
  validators: ^2.0.0+1
  dio: 2.1.13
  flutter_dotenv: ^2.1.0

  inject:
    git:
      # revert to google
      url: https://github.com/AndreySouza1/inject.dart.git
      ref: develop
      path: package/inject

  lib_di:
    path: ../lib_di
  lib_lego:
    path: ../lib_lego
  lib_locale:
    path: ../lib_locale

  flutter:
    sdk: flutter

dependency_overrides:
  source_gen: 0.9.4+6
  analyzer: ^0.39.2+1

dev_dependencies:

  json_serializable: ^3.2.3
  build_runner: ^1.7.2

  flutter_test:
    sdk: flutter

  inject_generator:
    git:
      url: https://github.com/AndreySouza1/inject.dart.git
      ref: develop
      path: package/inject_generator

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
