name: app_homepage
description: A new Flutter project.
version: 1.0.0+1
author: KodeSmil authors
homepage: kodesmil.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true