name: feat_profile
description: A new Flutter package project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  json_serializable: ^3.2.3
  intl: ^0.16.0
  google_sign_in: ^4.1.4
  provider: ^4.0.4
  smooth_star_rating: ^1.0.4+2
  url_launcher: ^5.4.7
  crossplat_objectid: ^2.1.4
  firebase_auth: ^0.16.1
  grpc: ^2.1.3
  transparent_image: ^1.0.0

  feat_auth:
    path: ../feat_auth
  feat_notifications:
    path: ../feat_notifications
  feat_storage:
    path: ../feat_storage
  lib_shared:
    path: ../../libs/lib_shared
  lib_lego:
    path: ../../libs/lib_lego
  lib_services:
    path: ../../libs/lib_services
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
