name: ably
description: A flutter boilerplate project created using MobX and Provider.
version: 0.0.8
author: KodeSmil authors
homepage: kodesmil.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4+6
  flutter_launcher_icons: ^0.7.4
  f_logs: ^1.2.1
  provider: ^4.0.4
  validators: ^2.0.0+1
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.2
  firebase_crashlytics: ^0.1.3+3
  firebase_admob: ^0.9.0+10
  flutter_dotenv: ^2.1.0
  grpc: ^2.1.3
  dynamic_theme: ^1.0.1

  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  json_serializable: ^3.2.3

  google_sign_in: ^4.1.4
  firebase_auth: ^0.16.1
  firebase_auth_web: ^0.1.3+1
  flutter_translate: ^1.1.0

  feat_storage:
    path: ../../features/feat_storage
  feat_ion:
    path: ../../features/feat_ion
  feat_auth:
    path: ../../features/feat_auth
  feat_splash:
    path: ../../features/feat_splash
  feat_chat:
    path: ../../features/feat_chat
  feat_onboarding:
    path: ../../features/feat_onboarding
  feat_profile:
    path: ../../features/feat_profile
  feat_journal:
    path: ../../features/feat_journal
  feat_health:
    path: ../../features/feat_health
  feat_notifications:
    path: ../../features/feat_notifications
  feat_services:
    path: ../../features/feat_services
  feat_feed:
    path: ../../features/feat_feed
  lib_shared:
    path: ../../libs/lib_shared
  lib_lego:
    path: ../../libs/lib_lego
  lib_services:
    path: ../../libs/lib_services

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/women/
    - assets/images/peach/
    - assets/images/peach/example/
    - assets/images/peach/characters/
    - assets/i18n/
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700