name: feat_services
description: A new Flutter package project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.1.0
  flutter_markdown: ^0.3.5
  flutter_svg: ^0.18.1
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  intl: ^0.16.0
  provider: ^4.0.4
  firebase_auth: ^0.18.0+1
  grpc: ^2.2.0
  smooth_star_rating: ^1.1.1
  uuid: ^2.0.4
  rxdart: ^0.24.1
  more: ^2.3.1
  mutex: ^1.1.0

  cupertino_icons: ^0.1.2
  flutter_icons: ^0.1.3
  flutter_webrtc: ^0.3.2
  flutter_ion:
    git:
      url: git://github.com/kodesmil/ion-sdk-flutter.git
  shared_preferences: ^0.5.7
  date_format: ^1.0.6
  quiver: ^2.1.3

  feat_auth:
    path: ../feat_auth
  feat_storage:
    path: ../feat_storage

  lib_shared:
    path: ../../libs/lib_shared
  lib_lego:
    path: ../../libs/lib_lego
  lib_services:
    path: ../../libs/lib_services

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
