name: app_kodesmil_homepage
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  url_launcher: ^5.4.1
  url_launcher_web: ^0.1.0+2
  cupertino_icons: ^0.1.2
  flutter_widgets: ^0.1.9
  auto_size_text: ^2.1.0
  intercom_flutter: ^2.0.7
  flutter_svg:
    git:
      url: git@github.com:feilfeilundfeil/flutter_svg.git
      branch: feature/web
  lib_lego:
    path: ../lib_lego
  lib_locale:
    path: ../lib_locale

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/Noto/NotoSansDisplay-Thin.ttf
          weight: 200
        - asset: assets/fonts/Noto/NotoSansDisplay-Regular.ttf
        - asset: assets/fonts/Noto/NotoSansDisplay-Bold.ttf
          weight: 600