name: module_sensors
description: A new Flutter package project.
author: KodeSmil authors
homepage: kodesmil.com
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter_sensors: ^0.1.5
  csv: ^4.0.3
  flutter_email_sender: ^2.2.2
  path_provider: ^1.6.0
  archive: ^2.0.11
  flutter_mobx: ^0.3.6
  mobx: ^0.4.0+1
  mobx_codegen: ^0.3.13
  json_serializable: ^3.2.3
  intl: ^0.16.0
  lib_di:
    path: ../../libs/lib_di
  lib_lego:
    path: ../../libs/lib_lego
  kodesmil_locale:
    path: ../../translations/kodesmil_locale
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
